name: 'Install Dependencies'
description: 'Installs wheel and third-party dependencies.'
runs:
  using: 'composite'
  steps:
    - name: Setup python by installing wheel
      run: pip install wheel==0.35.0
      shell: bash
    - name: Check Yarn Cache
      run: |
        # Move outside repository root to ignore the configs in
        # oppia/.yarnrc. These configs specify that yarn should use the
        # Oppia-managed yarn executable, which hasn't been downloaded
        # yet.
        cd ..
        # Create a new .yarnrc file to check what is already in the
        # Oppia-managed yarn cache.
        echo 'cache-folder "yarn_cache"' > .yarnrc
        yarn cache list
        # Delete the .yarnrc file that we just created.
        rm .yarnrc
        # Move back to the repository root.
        cd -
      shell: bash
    # Production pip dependencies are installed in a custom folder rather than
    # the pip cache (see "Caching Python dependencies" in the README at
    # https://github.com/actions/setup-python?tab=readme-ov-file).
    #
    # This means that using the cache provided by the setup-python action above
    # doesn't work for global dependencies. So, instead, we follow the "Best
    # Practice" in this comment and cache that directory directly:
    # https://github.com/actions/setup-python/issues/881#issuecomment-2147747696
    #
    # Note that, in the case of a cache miss, the cache is populated when the
    # job completes successfully. See
    # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#cache-hits-and-misses
    - name: Write the exact Python version to a file for cache-busting.
      run: |
        echo "${{ steps.setup_python.outputs.python-version }}" > /home/runner/work/.pyversion
      shell: bash
    - name: Cache third_party and node_modules
      id: restore_third_party_and_node_modules_cache
      uses: actions/cache@v4
      with:
        # We don't use the restore-keys option, since the hash in the key
        # should fully define the cache. See https://stackoverflow.com/a/74620917
        # for some useful context on cases in which restore-keys is useful.
        #
        # Note that we need to include install_python_dev_dependencies.py in
        # the cache key because it has the version numbers for pip, pip-tools
        # and setuptools.
        key: ${{ runner.os }}-proddeps-${{ hashFiles('/home/runner/work/.pyversion', 'yarn.lock', 'requirements_dev.txt', 'requirements.txt', 'dependencies.json',  'scripts/install_python_dev_dependencies.py') }}
        path: |
          /home/runner/work/oppia/oppia_tools
          /home/runner/work/oppia/yarn_cache
          /home/runner/work/oppia/oppia/node_modules
          /home/runner/work/oppia/oppia/third_party/python_libs
          /home/runner/work/oppia/oppia/third_party/static
    - name: Install third-party libs on cache miss (retries on error)
      if: steps.restore_third_party_and_node_modules_cache.outputs.cache-hit == false
      uses: nick-fields/retry@v3
      with:
        max_attempts: 3
        retry_on: error
        shell: bash
        timeout_minutes: 30
        command: python -m scripts.install_third_party_libs
    - name: Check Yarn Cache
      # Check the yarn cache again to see what packages were just
      # installed.
      run: yarn cache list
      shell: bash
