name: Merge develop and set up Python
description: 'Merge develop into current branch, and set up Python'
runs:
  using: composite
  steps:
    - name: Merge develop branch into the current branch
      uses: ./.github/actions/merge
    - name: Setup Python 3.9.20
      uses: actions/setup-python@v5
      id: setup_python
      with:
        python-version: '3.9.20'
        architecture: 'x64'
        cache: 'pip'
        cache-dependency-path: |
          requirements_dev.txt
    - name: Show whether a cache hit occurred (for debugging purposes).
      run: |
        echo "${{ steps.setup_python.outputs.cache-hit }}"
      shell: bash
    - name: Write the exact Python version to a file for cache-busting.
      run: |
        echo "${{ steps.setup_python.outputs.python-version }}" > /home/runner/work/.pyversion
      shell: bash
    - name: Cache Python dev dependencies
      id: restore_python_dev_dependencies_cache
      uses: actions/cache@v4
      # We need to include install_python_dev_dependencies.py in the cache key
      # because it has the version numbers for pip, pip-tools and setuptools.
      with:
        key: ${{ runner.os }}-proddeps-${{ hashFiles('/home/runner/work/.pyversion', 'requirements_dev.txt', 'scripts/install_python_dev_dependencies.py') }}
        path: |
          /opt/hostedtoolcache/Python/3.9.20/x64
    - name: Install third-party Python dev dependencies
      if: steps.restore_python_dev_dependencies_cache.outputs.cache-hit == false
      uses: nick-fields/retry@v3
      with:
        max_attempts: 3
        retry_on: error
        shell: bash
        timeout_minutes: 30
        # Note that the effects of this don't seem to be cached by setup-python,
        # resulting in the occasional "No module named PIL" errors in CI.
        command: python -m scripts.install_python_dev_dependencies
    - name: Show where pip installs its packages, and the contents of that folder.
      run: |
        pip show certifi
        ls -la /opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages
        ls -la /opt/hostedtoolcache/Python/3.9.20/x64/bin
      shell: bash
