name: Lint Checks
on:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  lint:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        shard: ['other']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Merge develop and set up Python
        uses: ./.github/actions/merge-develop-and-setup-python
        with:
          use_cache: false
      - name: Initialize Docker containers
        uses: ./.github/actions/install-oppia-dependencies-docker
      - name: Third Party Size Check
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: make run_tests.third_party_size_check
      - name: Run Lint Checks
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: make run_tests.lint PYTHON_ARGS="--shard ${{ matrix.shard }} --verbose"
      - name: Report failure if failed on oppia/oppia develop branch
        if: ${{ failure() && github.event_name == 'push' && github.repository == 'oppia/oppia' && github.ref == 'refs/heads/develop'}}
        uses: ./.github/actions/send-webhook-notification
        with:
          message: "Lint checks failed on the upstream develop branch."
          webhook-url: ${{ secrets.BUILD_FAILURE_ROOM_WEBHOOK_URL }}
