name: Process New Pull Request

on:
  pull_request:
    types: [opened]

permissions: read-all
jobs:
  assign_reviewers:
    name: Assign Reviewers
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Assign Reviewers
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { pull_request, repository } = context.payload;
            const owner = repository.owner.login;
            const repo = repository.name;
            const prNumber = pull_request.number;
            const submitterUsername = pull_request.user.login;

            // Fetch merged PRs of the submitter
            const mergedPRs = await github.pulls.list({
              owner,
              repo,
              state: "merged",
              per_page: 5,
              sort: "created",
              direction: "desc",
            });

            const submitterIsNewContributor = mergedPRs.data.length === 0;

            console.log(
              `User @${submitterUsername} is ${
                submitterIsNewContributor
                  ? 'a new contributor'
                  : 'not a new contributor'
              }.`
            );

            // Get reviewers from CODEOWNERS
            const requestedReviewers = pull_request.requested_reviewers.map(r => r.login);
            const requestedTeams = pull_request.requested_teams.map(t => t.slug);

            // Assign reviewers as assignees
            if (requestedReviewers.length > 0) {
              await github.issues.addAssignees({
                owner,
                repo,
                issue_number: prNumber,
                assignees: requestedReviewers,
              });
              console.log(
                `Assigned reviewers: ${requestedReviewers.join(", ")}`
              );
            }

            // Notify team if no individual reviewers are found
            if (requestedReviewers.length === 0) {
              console.log(
                "No individual reviewers found in CODEOWNERS. Notifying the team."
              );
              await github.issues.createComment({
                owner,
                repo,
                issue_number: prNumber,
                body: `No individual reviewers were found by GitHub. Please assign an appropriate reviewer. @oppia/dev-workflow-reviewers, could you please review the issue? Thank you!`,
              });
            }

            // Add PTAL syntax comment only for new contributors
            if (submitterIsNewContributor) {
              const commentBody = `Hello @${submitterUsername}! Thank you for making a PR. Please ensure your PR is assigned to the correct reviewers -- check the "Assignees" section in the sidebar on the right. Typically, this should match the "Reviewers" section. If it's not correct, you can leave a comment with the syntax \`@reviewer_username PTAL\` to request that a specific reviewer be assigned.\n\n Thanks!`;

              await github.issues.createComment({
                owner,
                repo,
                issue_number: prNumber,
                body: commentBody,
              });
              console.log(
                `Added PTAL syntax comment for new contributor @${submitterUsername}.`
              );
            }
