name: Test coverage and Typescript test
on:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  e2e_acceptance_coverage_and_typescript_tests:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Merge develop and set up Python
        uses: ./.github/actions/merge-develop-and-setup-python
        with:
          use_cache: false
      - name: Install Chrome
        uses: ./.github/actions/install-chrome
      - name: Initialize Containers
        uses: ./.github/actions/install-oppia-dependencies-docker
      - name: Check that all e2e test files are captured in wdio.conf.js
        run: make run_tests.check_tests_are_captured_in_ci
      - name: Run typescript tests
        run: make run_tests.typescript
      - name: Run typescript tests in strict mode
        run: make run_tests.typescript PYTHON_ARGS="--strict_checks"
      - name: Report failure if failed on oppia/oppia develop branch
        if: ${{ failure() && github.event_name == 'push' && github.repository == 'oppia/oppia' && github.ref == 'refs/heads/develop'}}
        uses: ./.github/actions/send-webhook-notification
        with:
          message: "A typescript test failed on the upstream develop branch."
          webhook-url: ${{ secrets.BUILD_FAILURE_ROOM_WEBHOOK_URL }}
